use crate::stores::{auth_store, dms, nostr_client};
use dioxus::prelude::*;

const CSAE_CONTACT_NPUB: &str = "npub10vz2md22xl8arjprqysn8f7j2guewzunaktnn94c55hlwcwyyu4qm6ac8k";
const SEND_COOLDOWN_MS: u32 = 5_000;

#[component]
pub fn Csae() -> Element {
    let mut summary = use_signal(String::new);
    let mut details = use_signal(String::new);
    let mut follow_up = use_signal(String::new);
    let mut sending = use_signal(|| false);
    let mut send_cooldown = use_signal(|| false);
    let mut send_feedback = use_signal(|| None::<(bool, String)>);

    let current_pubkey = auth_store::get_pubkey();

    let send_child_safety_message = move |_| {
        let summary_value = summary.read().trim().to_string();
        let details_value = details.read().trim().to_string();
        let follow_up_value = follow_up.read().trim().to_string();

        if details_value.is_empty() || *sending.read() || *send_cooldown.read() {
            return;
        }

        sending.set(true);
        send_feedback.set(None);

        spawn(async move {
            let recipient = match crate::utils::nip19::normalize_pubkey(CSAE_CONTACT_NPUB) {
                Ok(pubkey) => pubkey,
                Err(e) => {
                    sending.set(false);
                    send_feedback.set(Some((
                        false,
                        format!("Invalid safety contact pubkey: {}", e),
                    )));
                    return;
                }
            };

            let mut message_parts = vec!["nostr.blue child safety report".to_string()];

            if let Some(reporter_pubkey) = auth_store::get_pubkey() {
                message_parts.push(format!("Reporter pubkey: {}", reporter_pubkey));
            } else {
                message_parts.push(
                    "Reporter identity: temporary local key generated by nostr.blue".to_string(),
                );
            }

            if !summary_value.is_empty() {
                message_parts.push(format!("Summary: {}", summary_value));
            }

            if !follow_up_value.is_empty() {
                message_parts.push(format!("Preferred follow-up contact: {}", follow_up_value));
            }

            message_parts.push("Details:".to_string());
            message_parts.push(details_value);

            let send_result = if nostr_client::has_signer() {
                dms::send_dm(recipient, message_parts.join("\n\n")).await
            } else {
                dms::send_dm_with_temporary_keys(recipient, message_parts.join("\n\n")).await
            };

            match send_result {
                Ok(result) => {
                    sending.set(false);
                    if result.is_success() {
                        summary.set(String::new());
                        details.set(String::new());
                        follow_up.set(String::new());
                        send_cooldown.set(true);
                        spawn(async move {
                            crate::platform::timer::sleep_ms(SEND_COOLDOWN_MS).await;
                            send_cooldown.set(false);
                        });
                        if result.has_failures() {
                            send_feedback.set(Some((
                                true,
                                format!(
                                    "Message sent to {}/{} relays.",
                                    result.success_count(),
                                    result.total_attempted(),
                                ),
                            )));
                        } else {
                            send_feedback.set(Some((
                                true,
                                "Message sent to the nostr.blue child safety contact.".to_string(),
                            )));
                        }
                    } else {
                        send_feedback.set(Some((
                            false,
                            "No relay accepted the message. You can also email abuse@nostr.blue."
                                .to_string(),
                        )));
                    }
                }
                Err(e) => {
                    sending.set(false);
                    send_feedback.set(Some((
                        false,
                        format!(
                            "Could not send the message: {}. You can also email abuse@nostr.blue.",
                            e
                        ),
                    )));
                }
            }
        });
    };

    rsx! {
        div { class: "max-w-4xl mx-auto px-6 py-12",
            h1 { class: "text-4xl font-bold mb-8", "Child Safety Standards" }
            div { class: "prose dark:prose-invert max-w-none space-y-6",
                p { class: "text-lg text-muted-foreground", "Last updated: March 25, 2026" }

                section { class: "space-y-4",
                    h2 { class: "text-2xl font-semibold mt-8", "1. Overview" }
                    p {
                        "nostr.blue has zero tolerance for child sexual abuse and exploitation (CSAE) and child sexual abuse material (CSAM). These standards apply to the nostr.blue app and its use across the web app, Android app, and native desktop app."
                    }
                    p {
                        "You may not use nostr.blue to create, upload, post, request, promote, organize, distribute, discover, or facilitate sexual exploitation of minors."
                    }
                }

                section { class: "space-y-4",
                    h2 { class: "text-2xl font-semibold mt-8", "2. Prohibited Content And Conduct" }
                    p { "Content or behavior prohibited in nostr.blue includes, at minimum:" }
                    ul { class: "list-disc pl-6 space-y-2",
                        li { "Any CSAM or other sexualized depiction of minors, including real, manipulated, or computer-generated imagery" }
                        li { "Grooming, sextortion, trafficking, solicitation, or coercion involving a minor" }
                        li { "Using nostr.blue to sexualize, exploit, endanger, or abuse children" }
                        li { "Sharing links, hashes, identifiers, or instructions intended to access or distribute CSAM" }
                        li { "Attempting to use private messages, profiles, media uploads, comments, communities, or any other app feature to facilitate CSAE" }
                    }
                }

                section { class: "space-y-4",
                    h2 { class: "text-2xl font-semibold mt-8", "3. Reporting And User Feedback" }
                    p {
                        "nostr.blue provides in-app content reporting controls and a dedicated in-app child safety contact form on this page. If you are not signed in, nostr.blue can generate a temporary local key to send the message."
                    }
                    p {
                        "If you believe a child is in immediate danger, contact local law enforcement immediately."
                    }
                }

                section { class: "space-y-4",
                    h2 { class: "text-2xl font-semibold mt-8", "4. In-App Child Safety Contact" }
                    p {
                        "You can send a child safety concern to nostr.blue from inside the app. Signed-in users with a signer can send an encrypted NIP-17 message using their current account. If you are not signed in with a signer, nostr.blue can generate a temporary local key for this message. You can also use "
                        a {
                            href: "mailto:abuse@nostr.blue",
                            class: "text-blue-500 hover:underline",
                            "abuse@nostr.blue"
                        }
                        "."
                    }

                    div { class: "not-prose rounded-xl border border-border bg-card p-5 space-y-4",
                        div { class: "space-y-1",
                            h3 { class: "text-lg font-semibold text-foreground", "Send Child Safety Message" }
                            p { class: "text-sm text-muted-foreground",
                                "Recipient: "
                                code { class: "font-mono text-xs", "{CSAE_CONTACT_NPUB}" }
                            }
                            if let Some(pubkey) = current_pubkey.as_ref() {
                                p { class: "text-sm text-muted-foreground",
                                    "Sending as: "
                                    code { class: "font-mono text-xs", "{pubkey}" }
                                }
                            } else {
                                p { class: "text-sm text-muted-foreground",
                                    "Not signed in: nostr.blue will generate a temporary local key for this message."
                                }
                            }
                        }

                        div { class: "space-y-4",
                            div { class: "space-y-2",
                                label { class: "block text-sm font-medium text-foreground", "Summary (optional)" }
                                input {
                                    class: "w-full rounded-lg border border-border bg-background px-3 py-2 text-sm text-foreground focus:outline-hidden focus:ring-2 focus:ring-blue-500",
                                    r#type: "text",
                                    maxlength: "140",
                                    placeholder: "Short summary of the concern",
                                    value: "{summary}",
                                    oninput: move |e| summary.set(e.value()),
                                }
                            }

                            div { class: "space-y-2",
                                label { class: "block text-sm font-medium text-foreground", "Details" }
                                textarea {
                                    class: "w-full min-h-40 rounded-lg border border-border bg-background px-3 py-2 text-sm text-foreground focus:outline-hidden focus:ring-2 focus:ring-blue-500 resize-y",
                                    placeholder: "Describe the concern, include any relevant event IDs, profile links, or other details.",
                                    value: "{details}",
                                    oninput: move |e| details.set(e.value()),
                                }
                            }

                            div { class: "space-y-2",
                                label { class: "block text-sm font-medium text-foreground", "Email Or Other Follow-Up Contact (optional)" }
                                input {
                                    class: "w-full rounded-lg border border-border bg-background px-3 py-2 text-sm text-foreground focus:outline-hidden focus:ring-2 focus:ring-blue-500",
                                    r#type: "text",
                                    placeholder: "How should we follow up if needed?",
                                    value: "{follow_up}",
                                    oninput: move |e| follow_up.set(e.value()),
                                }
                            }

                            if let Some((is_success, message)) = send_feedback.read().as_ref() {
                                div {
                                    class: if *is_success {
                                        "rounded-lg border border-green-500/30 bg-green-500/10 px-3 py-2 text-sm text-green-700 dark:text-green-300"
                                    } else {
                                        "rounded-lg border border-red-500/30 bg-red-500/10 px-3 py-2 text-sm text-red-700 dark:text-red-300"
                                    },
                                    "{message}"
                                }
                            }

                            div { class: "flex items-center justify-between gap-3",
                                p { class: "text-xs text-muted-foreground",
                                    if *send_cooldown.read() {
                                        "Please wait a few seconds before sending another report."
                                    } else if *nostr_client::HAS_SIGNER.read() {
                                        "This uses your current signer and nostr.blue's NIP-17 direct-message flow."
                                    } else {
                                        "This uses a temporary locally generated key and sends a NIP-17 receiver-only message."
                                    }
                                }
                                button {
                                    class: "rounded-lg bg-red-600 px-4 py-2 text-sm font-medium text-white transition hover:bg-red-700 disabled:opacity-50 disabled:cursor-not-allowed",
                                    disabled: details.read().trim().is_empty()
                                        || *sending.read()
                                        || *send_cooldown.read(),
                                    onclick: send_child_safety_message,
                                    if *sending.read() {
                                        "Sending..."
                                    } else if *send_cooldown.read() {
                                        "Please Wait..."
                                    } else {
                                        "Send Message"
                                    }
                                }
                            }
                        }
                    }
                }

                section { class: "space-y-4",
                    h2 { class: "text-2xl font-semibold mt-8", "5. How nostr.blue Responds" }
                    p {
                        "When we become aware of apparent CSAE or CSAM related to nostr.blue, we may take action consistent with applicable law and the technical limits of the product, including:"
                    }
                    ul { class: "list-disc pl-6 space-y-2",
                        li { "Hiding, filtering, blocking, or otherwise restricting content within app-controlled views where technically feasible" }
                        li { "Using app-level reporting, mute, block, and safety controls to reduce further exposure" }
                        li { "Escalating reports to relevant service providers, platforms, relays, media hosts, or authorities when appropriate or legally required" }
                        li { "Complying with valid legal process and child safety obligations" }
                    }
                }

                section { class: "space-y-4",
                    h2 { class: "text-2xl font-semibold mt-8", "6. Decentralized Network Notice" }
                    p {
                        "nostr.blue is a client for decentralized and third-party systems, including independent Nostr relays and media hosts. Because of that architecture, nostr.blue may not control or permanently remove content stored by third-party relays, hosts, wallets, or external services."
                    }
                    p {
                        "Even so, nostr.blue does not permit use of the app for CSAE or CSAM and will take app-side mitigation steps where technically and legally feasible."
                    }
                }

                section { class: "space-y-4",
                    h2 { class: "text-2xl font-semibold mt-8", "7. Compliance" }
                    p {
                        "nostr.blue intends to comply with applicable child safety laws and Google Play's Child Safety Standards requirements for social apps."
                    }
                }

                section { class: "space-y-4",
                    h2 { class: "text-2xl font-semibold mt-8", "8. Child Safety Contact" }
                    p {
                        "For child safety, CSAE, or CSAM related concerns involving nostr.blue, contact "
                        a {
                            href: "mailto:abuse@nostr.blue",
                            class: "text-blue-500 hover:underline",
                            "abuse@nostr.blue"
                        }
                        "."
                    }
                }

                section { class: "space-y-4",
                    h2 { class: "text-2xl font-semibold mt-8", "9. Related Pages" }
                    p {
                        "For more about the app, see our "
                        Link {
                            to: crate::routes::Route::About {},
                            class: "text-blue-500 hover:underline",
                            "About"
                        }
                        ", "
                        Link {
                            to: crate::routes::Route::Terms {},
                            class: "text-blue-500 hover:underline",
                            "Terms of Service"
                        }
                        ", and "
                        Link {
                            to: crate::routes::Route::Privacy {},
                            class: "text-blue-500 hover:underline",
                            "Privacy Policy"
                        }
                        "."
                    }
                }
            }
        }
    }
}
